font:
  normal:
    family: Iosevka
    style: Regular
  size: 12.0

colors:
  primary:
    background: "#121212"
    foreground: "#eeeeee"
  cursor:
    text: "#000000"
    background: "#fffdb5"
  normal:
    black: "#000000"
    red: "#cc0403"
    green: "#10e000"
    yellow: "#cecb00"
    blue: "#0d73e8"
    magenta: "#cb1ed1"
    cyan: "#0dcdcd"
    white: "#dddddd"
  bright:
    black: "#767676"
    red: "#f2201f"
    green: "#23fd00"
    yellow: "#fffd00"
    blue: "#1a8fff"
    magenta: "#fd28ff"
    cyan: "#14ffff"
    white: "#ffffff"

window:
  padding:
    x: 3
    y: 3
