#!/bin/sh

# More info: https://wiki.archlinux.org/title/Rsync#Full_system_backup

echo "WARNING! Lookup this script first and make sure that everyting is ok!"
while true; do
  read -p "Do you wish to continue? (y/n)" yn
    case $yn in
        [Yy]* ) break;;
        [Nn]* ) exit;;
        * ) echo "Please answer yes or no.";;
    esac
done

# rsync must be installed ofc
# external drive must be mounted to /mnt.

sudo rsync -aAXHv --delete --exclude={"/dev/*","/proc/*","/sys/*","/tmp/*","/run/*","/mnt/*","/media/*","/lost+found","/home/*/.cache/mozilla/*","/home/*/.cache/BraveSoftware/*"} / /mnt/backup
