#!/bin/sh

for i in {0..255} ; do
    printf "\x1b[48;5;0m\x1b[38;5;${i}m%3d" "${i}"
    printf "\x1b[48;5;${i}m%3d\x1b[38;5;0m" "${i}"
    if (( $i == 15 )) || (( $i > 15 )) && (( ($i-15) % 12 == 0 )); then
        printf "\x1b[48;5;0m\n";
    fi
done
