#!/bin/sh

# Headset must be connected and experimental feats must be enabled
# https://wiki.archlinux.org/title/Bluetooth#Enabling_experimental_features

case $BLOCK_BUTTON in
	1) connect-my-headset ;;
esac

BATTERY_PERCENT=$(upower --dump | grep -A3 'headset' | grep 'percentage' | tr -d -c 0-9 | sed -e 's/$/%/')
[ -z "$BATTERY_PERCENT" ] && echo -e "\uf7ca-" || echo -e "\uf7ca$BATTERY_PERCENT"
