#!/bin/sh

YTID=$(echo $1 | awk -F'=' '{print $2}')

if [ $(find ~/Videos/imp-videos -name "*$YTID*" | wc -l) -gt 0 ]
then
  echo "Video already downloaded."
else
  echo "Start downloading..."
  youtube-dl -o "~/Videos/imp-videos/%(title)s (%(id)s).%(ext)s" --write-description $1 > /dev/null 2>&1 &
fi
