#!/bin/sh

# Module showing network traffic. Shows how much data has been received (RX) or
# transmitted (TX) since the previous time this script ran. So if run every
# second, gives network traffic per second.

# case $BLOCK_BUTTON in
# 	1) setsid -f "$TERMINAL" -e bmon ;;
# 	3) notify-send "🌐 Network traffic module" "🔻: Traffic received
# 🔺: Traffic transmitted" ;;
# 	6) "$TERMINAL" -e "$EDITOR" "$0" ;;
# esac

# todo: check connected interface by nmcli

update() {
    sum=0
    for arg; do
        read -r i < "$arg"
        sum=$(( sum + i ))
    done
    cache=/tmp/${1##*/}
    [ -f "$cache" ] && read -r old < "$cache" || old=0
    printf %d\\n "$sum" > "$cache"
    printf %d\\n $(( sum - old ))
}

rx=$(update /sys/class/net/$MAIN_INTERNET_INTERFACE_NAME/statistics/rx_bytes)
tx=$(update /sys/class/net/$MAIN_INTERNET_INTERFACE_NAME/statistics/tx_bytes)

printf "|\u2198%4sB\u2197%4sB|\\n" $(numfmt --to=iec $rx $tx)
