#!/bin/sh

# Optional:
# youtube-dl -f bestaudio $1 --exec "ffmpeg -i {}  -codec:a libmp3lame -qscale:a 0 {}.mp3 && rm {} "

YTID=$(echo $1 | awk -F'=' '{print $2}')

if [ $(find ~/Music -name "*$YTID*" | wc -l) -gt 0 ]
then
  echo "Video already downloaded."
else
  echo "Start downloading..."
  youtube-dl --extract-audio --audio-format mp3 --audio-quality 0 -o "~/Music/%(title)s (%(id)s).%(ext)s" --write-description $1 > /dev/null 2>&1 &
fi
